### ISSUE TITLE
Ajuste de background

### ISSUE THREAD

**Issue by gabrielrusso6** [kiingsway/teams_viewer#1]
Ao acessar a ferramenta, nota-se as cores de fundo não apropriadas ao layout, sendo assim, tornando inviável a utilização.

Segue prints como evidências.
![Ferramenta Marcos](https://user-images.githubusercontent.com/56118446/203045708-7959eed2-50ea-496f-9c05-b03cca946497.png)

**Comment by kiingsway** [comment]
Corrigido no commit: https://github.com/kiingsway/teams_viewer/commit/948c3e3cb25de3626f3c5cd6701ab6e94dde36ed.
Foi identificado que o CSS gerado pelo Next vem com a funcionalidade "prefers-color-scheme", que foi removido e o estilo aplicado globalmente.
Obrigado pela abertura do problema!
